item {
  id: 1
  name: 'Aloevera'
}

item {
  id: 2
  name: 'Insulin'
}

item {
  id: 3
  name: 'Oregano'
}

item {
  id: 4
  name: 'Baston de san jose'
}

item {
  id: 5
  name: 'Pothos plant'
}

item {
  id: 6
  name: 'Snake plant'
}

item {
  id: 7
  name: 'Yellow and green leaf'
}